### ISSUE TITLE
Idea: web interface

### ISSUE THREAD

**Issue by abesto** [nickstenning/honcho#166]
Wondering what the general feeling is about something like a web interface for managing processes run by Honcho, for local development environments. Couple of things that could make it useful:

 * show at a glance which processes are running
 * one-click start / stop / restart for processes
 * filter logs on the front-end by string / regex
 * filter logs on the front-end by which process wrote the logs
 * click through to web processes

Is this an obviously bad idea for a reason I don't see? Is there already something like this? Should this be developed as part of `honcho`, or a stand-alone tool / wrapper?

**Comment by nickstenning** [comment]
This sounds like a great idea, but it would probably entail a fair number of additional dependencies, and thus I'd be reluctant for this to be part of Honcho itself. It is possible to use Honcho as a library rather than a command-line tool, so I'd suggest a standalone package that uses Honcho in this way is probably the best place to experiment with this idea.

Let us know if you build something and I'll happily link to it from our documentation!

**Comment by abesto** [comment]
Thanks for the input, makes total sense.

I've since started experimenting with an implementation using [Meteor](https://www.meteor.com/). That's node.js, so not based on Honcho. In case you're curious: https://github.com/abesto/procfile-web
