### ISSUE TITLE
[Question] Processes Lifecycycle

### ISSUE THREAD

**Issue by kuraga** [nickstenning/honcho#175]
Good day!

I started 3 processes. And due to log, two others got `SIGTERM` in the next moment after first process finished.

So, Honcho waits one process only? Thanks.

**Comment by nickstenning** [comment]
Honcho is intended for supervising/orchestrating long-running processes like web application servers or job workers. So yes, Honcho will exit and terminate other processes if one exits. This is intended behaviour.

**Comment by gowhari** [comment]
I could find it in the API doc:

> If one process terminates, all the others will be terminated by Honcho, and [loop()](https://honcho.readthedocs.io/en/latest/api.html#honcho.manager.Manager.loop) will return.

Normally, a supervising system would attempt to restart the terminated process rather than terminating all other processes, or at least some systems operate that way. It was confusing for me that what's happening at the beginning.

However, since Honcho follows this approach, it would be beneficial to emphasize it in the introductory section of the documentation.
